### ISSUE TITLE
Add POST body parsing to /public/guides/upgrade.md if needed

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#123]
Arc 5 used to parse bodies, Arc 6 does not:

> one of the tradeoffs that we had to make in v6. now payloads come in encoded (and thusly unparsed), but as brian mentioned, just run any bodies through the helper and you're g2g

Document this depending on how we want to handle this (see Slack discussion).

 - Parse bodies automatically (I like this if it's technically possible - if a request has a body, an Arc user probably wants to use it)

 - Modify `arc.http.helpers.bodyParser` to be Arc middleware (ie, just return the modified request) and tell people to use that. So people could run `exports.handler = arc.http.middleware(parseBody, http)`

**Comment by exalted** [comment]
At least aa of `v6.3.4` both `arc.http(...)` and `arc.http.async(…)` will already parse the body for you.

**Comment by tbeseda** [comment]
This issue is a bit old but I have noticed that there are occasional user issues where the body was expected to be parsed. So there's room for improvement in the docs around how vanilla arc works and how arc works with arc/functions.

I'm going to close this one in favor of a related, more recent issue: #311 -- It's more targeted at current points of friction
